AWSTemplateFormatVersion: "2010-09-09"
Description: Spring Boot App with ALB, Auto Scaling Group, CloudWatch Logs, Secrets Manager, and SQS.
Parameters:
  HostedZoneId:
    Type: String
    Default: Z088728234VIODEIPOBPH
    Description: "Route53 Hosted Zone ID for plansmartvoyager.com (pre-filled)."

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, HTTPS, MySQL, and custom ports
      VpcId: vpc-0481382a2919cabc9
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and HTTPS access to Load Balancer
      VpcId: vpc-0481382a2919cabc9
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MySpringBootALB
      Subnets:
        - subnet-050cfb6d7966c030c
        - subnet-0252389a16e6033e0
        - subnet-01572867f987c92be
      SecurityGroups:
        - !Ref ELBSecurityGroup
      Scheme: internet-facing
      Type: application
      IpAddressType: ipv4

  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: SpringBootTG
      Port: 80
      Protocol: HTTP
      VpcId: vpc-0481382a2919cabc9
      TargetType: instance
      HealthCheckPath: /students
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: 200

  MyListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup

  MyHTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:us-east-1:221082203021:certificate/ad576f8e-45c0-417e-8d12-f70a5293b523
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup

  MySecretsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: SecretsManagerAndSQSAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:us-east-1:221082203021:secret:aws-dev*
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:GetQueueUrl
                  - sqs:SendMessage
                Resource: arn:aws:sqs:us-east-1:221082203021:spring-boot-aws-queue
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::pallavishal
                  - arn:aws:s3:::pallavishal/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MySecretsRole
      Path: "/"

  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: SpringBootLT
      LaunchTemplateData:
        ImageId: ami-0c101f26f147fa7fd
        InstanceType: t2.medium
        IamInstanceProfile:
          Name: !Ref MyInstanceProfile
        SecurityGroupIds:
          - !Ref MySecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install wget -y
            yum install -y amazon-cloudwatch-agent
            yum install -y java-17-amazon-corretto
            yum remove -y maven
            yum install -y maven git wget

            git clone https://github.com/vishalkumar392392/aws-cloud-practioner-v2.git
            cd aws-cloud-practioner-v2/
            mvn clean package -Dmaven.test.skip=true
            cd target/
            mkdir -p /opt/springbootapp/
            cp *.jar /opt/springbootapp/app.jar
            mkdir -p /opt/springbootapp/logs/

            nohup java -jar /opt/springbootapp/app.jar > /opt/springbootapp/logs/app.log 2>&1 &

            cat > /opt/cloudwatch-config.json <<EOF
            {
              "logs": {
                "logs_collected": {
                  "files": {
                    "collect_list": [
                      {
                        "file_path": "/opt/springbootapp/logs/app.log",
                        "log_group_name": "/aws/ec2/springboot-app",
                        "log_stream_name": "{instance_id}-app-log",
                        "timestamp_format": "%Y-%m-%d %H:%M:%S"
                      }
                    ]
                  }
                }
              }
            }
            EOF

            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
              -a fetch-config \
              -m ec2 \
              -c file:/opt/cloudwatch-config.json \
              -s

  MyAppLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: /aws/ec2/springboot-app
      RetentionInDays: 7

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: MyAppLogGroup
    Properties:
      VPCZoneIdentifier:
        - subnet-050cfb6d7966c030c
        - subnet-0252389a16e6033e0
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      MinSize: 2
      MaxSize: 4
      DesiredCapacity: 2
      TargetGroupARNs:
        - !Ref MyTargetGroup
      MetricsCollection:
        - Granularity: "1Minute"
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300

  MyScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref MyAutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 50.0
        DisableScaleIn: false

  # Route53 record for springboot.plansmartvoyager.com
  SpringbootDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: springboot.plansmartvoyager.com.
      Type: A
      AliasTarget:
        DNSName: !GetAtt MyLoadBalancer.DNSName
        HostedZoneId: !GetAtt MyLoadBalancer.CanonicalHostedZoneID
        EvaluateTargetHealth: false

  # ------------- Lambda + Role + Custom Resource to start EC2 and update secret; stops instance on Delete -------------
  EC2StartLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CFN-StartEC2-UpdateSecret-Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: StartEC2AndManageSecrets
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:StartInstances
                  - ec2:StopInstances
                  - ec2:DescribeInstanceStatus
                Resource: "*"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:PutSecretValue
                Resource:
                  - arn:aws:secretsmanager:us-east-1:221082203021:secret:aws-dev-TTqsoc
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  EC2StartLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CFN_StartEC2_UpdateSecret
      Handler: index.handler
      Runtime: python3.9
      Role: !GetAtt EC2StartLambdaRole.Arn
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          TARGET_INSTANCE_ID: "i-02affc9bf3087e8f4"
          TARGET_SECRET_ARN: "arn:aws:secretsmanager:us-east-1:221082203021:secret:aws-dev-TTqsoc"
          TARGET_SECRET_KEY: "datasourceUrl"
          TARGET_DB_PORT: "3306"
          TARGET_DB_NAME: "school"
      Code:
        ZipFile: |
          import json
          import boto3
          import time
          import urllib.request
          import logging
          import os
          from urllib.error import URLError, HTTPError

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          ec2 = boto3.client('ec2')
          secrets = boto3.client('secretsmanager')

          def send_cfn_response(event, context, status, data=None, reason=None):
              """
              Send a response to the CloudFormation pre-signed S3 URL so CFN knows the custom resource result.
              """
              response_url = event.get('ResponseURL')
              response_body = {
                  'Status': status,
                  'Reason': reason or ('See the details in CloudWatch Log Stream: ' + context.log_stream_name),
                  'PhysicalResourceId': os.environ.get('TARGET_INSTANCE_ID', context.log_stream_name),
                  'StackId': event.get('StackId'),
                  'RequestId': event.get('RequestId'),
                  'LogicalResourceId': event.get('LogicalResourceId'),
                  'Data': data or {}
              }
              json_response = json.dumps(response_body).encode('utf-8')
              req = urllib.request.Request(response_url, data=json_response, method='PUT')
              req.add_header('Content-Type', 'application/json')
              req.add_header('Content-Length', str(len(json_response)))
              try:
                  with urllib.request.urlopen(req) as f:
                      logger.info("CloudFormation returned status code: %s", f.getcode())
              except HTTPError as e:
                  logger.error("HTTPError while sending response: %s", e.code)
              except URLError as e:
                  logger.error("URLError while sending response: %s", e.reason)
              except Exception as e:
                  logger.exception("Unexpected error while sending CFN response: %s", e)

          def get_public_ip(instance_id, timeout_seconds=240, sleep_interval=5):
              elapsed = 0
              while elapsed < timeout_seconds:
                  resp = ec2.describe_instances(InstanceIds=[instance_id])
                  reservations = resp.get('Reservations', [])
                  if reservations and reservations[0].get('Instances'):
                      inst = reservations[0]['Instances'][0]
                      state = inst.get('State', {}).get('Name')
                      public_ip = inst.get('PublicIpAddress')
                      logger.info("Instance state: %s, public ip: %s", state, public_ip)
                      if state == 'running' and public_ip:
                          return public_ip
                  time.sleep(sleep_interval)
                  elapsed += sleep_interval
              raise Exception("Timed out waiting for public IP on instance " + instance_id)

          def handler(event, context):
              logger.info("Received event: %s", json.dumps(event))
              request_type = event.get('RequestType')
              props = event.get('ResourceProperties', {})
              instance_id = props.get('InstanceId') or os.environ.get('TARGET_INSTANCE_ID')
              secret_arn = props.get('SecretArn') or os.environ.get('TARGET_SECRET_ARN')
              secret_key = props.get('SecretKey') or os.environ.get('TARGET_SECRET_KEY')
              db_port = props.get('DBPort') or os.environ.get('TARGET_DB_PORT')
              db_name = props.get('DBName') or os.environ.get('TARGET_DB_NAME')

              try:
                  if request_type == 'Delete':
                      # Stop the EC2 instance as part of stack deletion
                      logger.info("Delete request received — attempting to stop instance %s", instance_id)
                      try:
                          ec2.stop_instances(InstanceIds=[instance_id])
                          # optionally wait for stopped state (short loop)
                          waiter_elapsed = 0
                          while waiter_elapsed < 120:
                              resp = ec2.describe_instances(InstanceIds=[instance_id])
                              state = resp['Reservations'][0]['Instances'][0]['State']['Name']
                              logger.info("Current instance state: %s", state)
                              if state == 'stopped':
                                  break
                              time.sleep(5)
                              waiter_elapsed += 5
                          send_cfn_response(event, context, "SUCCESS", {"Message": "Instance stop requested on Delete"})
                      except Exception as e:
                          logger.exception("Failed to stop instance on Delete")
                          send_cfn_response(event, context, "FAILED", {}, reason=str(e))
                      return

                  if request_type not in ['Create', 'Update']:
                      send_cfn_response(event, context, "SUCCESS", {"Message": f"No-op for {request_type}"})
                      return

                  # For Create and Update: ensure running, fetch public IP, update secret key only
                  logger.info("Create/Update request — ensuring instance %s is running", instance_id)
                  desc = ec2.describe_instances(InstanceIds=[instance_id])
                  inst = desc.get('Reservations', [])[0].get('Instances', [])[0]
                  state = inst.get('State', {}).get('Name')
                  logger.info("Instance %s current state: %s", instance_id, state)

                  if state != 'running':
                      logger.info("Starting instance %s", instance_id)
                      ec2.start_instances(InstanceIds=[instance_id])
                  else:
                      logger.info("Instance %s already running", instance_id)

                  public_ip = get_public_ip(instance_id)
                  logger.info("Obtained public IP: %s", public_ip)

                  new_datasource = f"jdbc:mysql://{public_ip}:{db_port}/{db_name}"

                  # Fetch current secret (preserve other keys)
                  sec = secrets.get_secret_value(SecretId=secret_arn)
                  secret_string = sec.get('SecretString')
                  secret_obj = {}
                  if secret_string:
                      try:
                          secret_obj = json.loads(secret_string)
                          if not isinstance(secret_obj, dict):
                              # If JSON but not object, wrap it
                              secret_obj = {"value": secret_obj}
                      except Exception as e:
                          # not JSON — preserve original string under 'value'
                          logger.info("SecretString not JSON; wrapping original value under 'value' key")
                          secret_obj = {"value": secret_string}

                  # Update only the specified key
                  secret_obj[secret_key] = new_datasource

                  # Write back the secret preserving other keys
                  secrets.put_secret_value(SecretId=secret_arn, SecretString=json.dumps(secret_obj))

                  send_cfn_response(event, context, "SUCCESS", {"PublicIp": public_ip, "DatasourceUrl": new_datasource})
              except Exception as e:
                  logger.exception("Handler failed")
                  send_cfn_response(event, context, "FAILED", {}, reason=str(e))

  EC2StartCustomResource:
    Type: Custom::StartEC2AndUpdateSecret
    Properties:
      ServiceToken: !GetAtt EC2StartLambdaFunction.Arn
      InstanceId: "i-02affc9bf3087e8f4"
      SecretArn: "arn:aws:secretsmanager:us-east-1:221082203021:secret:aws-dev-TTqsoc"
      SecretKey: "datasourceUrl"
      DBPort: "3306"
      DBName: "school"

Outputs:
  LoadBalancerDNS:
    Description: DNS name of the Load Balancer
    Value: !GetAtt MyLoadBalancer.DNSName

  AppURL:
    Description: URL for the application (HTTPS)
    Value: !Sub "https://springboot.plansmartvoyager.com"

  EC2StartedPublicIP:
    Description: Public IP assigned to the started instance (from custom resource)
    Value: !GetAtt EC2StartCustomResource.PublicIp
