#!/bin/bash
# Update the system packages
sudo yum update -y

# Install Java 17 (Amazon Corretto)
sudo yum install java-17-amazon-corretto -y

# Remove any existing Maven installation
sudo yum remove maven -y

# Install Maven
sudo yum install maven -y

# Install Git
sudo yum install git -y

dnf update -y

# Install wget
dnf install -y wget


# Download MySQL 8.0 repository package
wget https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm

# Install the repository package
dnf install -y mysql80-community-release-el9-1.noarch.rpm

# Import MySQL GPG key
rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023

# Install MySQL server
dnf install -y mysql-community-server

# Start and enable MySQL service
systemctl start mysqld
systemctl enable mysqld

# Retrieve temporary root password
TEMP_PASS=$(grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}')

# Define new MySQL root password
NEW_ROOT_PASS="MyStrongRootPass123!"
NEW_USER="newuser"
NEW_USER_PASS="StrongPassword123!"

# Secure MySQL installation (set new root password)
mysql --connect-expired-password -u root -p"$TEMP_PASS" <<EOF
ALTER USER 'root'@'localhost' IDENTIFIED WITH 'caching_sha2_password' BY '$NEW_ROOT_PASS';
CREATE USER 'root'@'%' IDENTIFIED BY '$NEW_ROOT_PASS';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF

# Create a new user and grant access to all IPs
mysql -u root -p"$NEW_ROOT_PASS" <<EOF
CREATE USER '$NEW_USER'@'%' IDENTIFIED BY '$NEW_USER_PASS';
GRANT ALL PRIVILEGES ON *.* TO '$NEW_USER'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF

# Allow MySQL to listen on all IPs (modify my.cnf.d/mysqld.cnf)
sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' /etc/my.cnf.d/mysqld.cnf

# Restart MySQL to apply changes
systemctl restart mysqld

# (Optional) Open MySQL port in firewall
firewall-cmd --permanent --add-service=mysql
firewall-cmd --reload
